spring.application.name=bus
server.port=8081

spring.mongodb.uri=mongodb://root:mongodb123456789@ac-6fwvdsc-shard-00-00.ghyuegk.mongodb.net:27017,ac-6fwvdsc-shard-00-01.ghyuegk.mongodb.net:27017,ac-6fwvdsc-shard-00-02.ghyuegk.mongodb.net:27017/?ssl=true&replicaSet=atlas-x055qh-shard-0&authSource=admin&appName=BusApp
spring.mongodb.database=BusApp
